version: "3.8"

services:
    cassandra:
        image: cassandra:latest
        container_name: cassandra_container
        restart: always
        environment:
            CASSANDRA_CLUSTER_NAME: "MyCluster"
            CASSANDRA_NUM_TOKENS: 256
            CASSANDRA_DC: "datacenter1"
            CASSANDRA_RACK: "rack1"
        ports:
            - "9042:9042"
        volumes:
            - cassandra_data:/var/lib/cassandra
            - ./cassandra-init:/cassandra-init # Katalog z plikami CQL

    cassandra-web:
        image: ipushc/cassandra-web
        container_name: cassandra_web
        restart: always
        environment:
            CASSANDRA_CONTACT_POINTS: cassandra
        ports:
            - "3000:3000"
        depends_on:
            - cassandra

    cqlsh:
        image: instaclustr/cassandra-cqlsh
        container_name: cassandra_cqlsh
        depends_on:
            - cassandra
        volumes:
            - ./cassandra-init:/cassandra-init
        entrypoint: /bin/sh -c "sleep 30 && for file in /cassandra-init/*.cql; do echo Running $file && cqlsh cassandra -f $file; done"

volumes:
    cassandra_data:
        driver: local
