version: "3.8"

services:
    cassandra:
        image: cassandra:latest
        container_name: cassandra_container
        restart: always
        environment:
            CASSANDRA_CLUSTER_NAME: "MyCluster"
            CASSANDRA_NUM_TOKENS: 256
            CASSANDRA_DC: "datacenter1"
            CASSANDRA_RACK: "rack1"
        ports:
            - "9042:9042"
        volumes:
            - cassandra_data:/var/lib/cassandra
            - ./init-cassandra.cql:/init-cassandra.cql
        healthcheck:
            test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
            interval: 30s
            timeout: 10s
            retries: 5

    cassandra-web:
        image: ipushc/cassandra-web
        container_name: cassandra_web
        restart: always
        environment:
            CASSANDRA_CONTACT_POINTS: cassandra
        ports:
            - "8083:8083"
        depends_on:
            - cassandra

    cqlsh:
        image: cassandra:latest # Zmieniono obraz na oficjalny Cassandra
        container_name: cassandra_cqlsh
        depends_on:
            - cassandra
        volumes:
            - ./init-cassandra.cql:/init-cassandra.cql
        entrypoint: /bin/sh -c "sleep 30 && for file in /init-cassandra.cql; do echo Running $$file && cqlsh cassandra -f $$file; done"

volumes:
    cassandra_data:
        driver: local

