version: "3.8"

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_container
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: wypozyczalnia
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js # Katalog z plikami inicjalizacyjnymi

    mongo-express:
        image: mongo-express
        container_name: mongo_express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: user
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - "8081:8081"
        depends_on:
            - mongodb

volumes:
    mongo_data:
        driver: local
