version: "3.8"

services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: my_database
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_container
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: user@user.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - "8082:80"
        depends_on:
            - postgres
        volumes:
            - ./add_pgadmin_server.sh:/docker-entrypoint-initdb.d/add_pgadmin_server.sh

volumes:
    postgres_data:
        driver: local

